on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['10', '12', '13', '14']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn --cwd packages/demo prod
